export const REQUEST_PEERS = 'REQUEST_PEERS';
export const LOAD_PEERS_SUCCESS = 'LOAD_PEERS_SUCCESS';
export const LOAD_PEERS_ERROR = 'LOAD_PEERS_ERROR';

export const REQUEST_COMPANY = 'REQUEST_COMPANY';
export const LOAD_COMPANY_RESPONSE = 'LOAD_COMPANY_RESPONSE';
export const LOAD_COMPANY_ERROR = 'LOAD_COMPANY_ERROR';
export const FETCHING_COMPANY = 'FETCHING_COMPANY';